---
  hosts: localhost
  become: true

  vars:
   http_port: 80
   domain: leodis.ac.uk
   shortdomain: leodis
   alias: "leodis.ac.uk leodis.co.uk www.leodis.co.uk leodis.net www.leodis.net"

  tasks:
   - name: install apache2
     apt: name=apache2 update_cache=yes state=latest

   - name: enable mod_proxy
     apache2_module: name=proxy state=present
     notify:
      - restart apache2

   - name: apache2 listen on port {{ http_port }}
     lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
     notify:
      - restart apache2

   - name: apache2 virtualhost on port {{ http_port }}
     lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
     notify:
      - restart apache2

    - name: create virtual host file
      template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ shortdomain }}.conf
      become: true

    - name: a2ensite {{ shortdomain }}
      command: a2ensite {{ shortdomain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ shortdomain }}.conf
      notify:
       - restart apache2

   handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
      become: true
